### ISSUE TITLE
Audio plays back too quickly on macOS.

### ISSUE THREAD

**Issue by emctague** [kondrak/vkQuake2#117] opened 2021-01-02 21:16 UTC
All the audio for the game is playing back faster than usual, causing all sounds to be chipmunk'd. - enemies sound absolutely hilarious, environmental sounds are off, etc.

Tried: adjusting in game audio quality settings, adjusting s_khz. No change.

Paks: Standard Quake2 paks off Steam release.
OS / Platform: MacOS Big Sur
Config.cfg: [here](https://gist.github.com/emctague/526363aec34d06cefe3699b0b25ab8e5)
vkQuake2 version: commit ef49294ae860a4892d9caf82fef8b494b0f9e1a0 (latest on master as of Jan 2, 2020)
VulkanSDK VERSIONS.txt: ~~[here](https://gist.github.com/emctague/c94c9102a4d2252ad02fb85c8cbbf68e)~~ latest as of today

~~I am currently updating my VulkanSDK to the latest December release, I will close this issue if Audio issues resolve after that but I doubt it.~~ (Audio still broken after update.)

**Comment by kondrak** [comment] 2021-01-03 09:30
Weird - did you get a chance to test it on Catalina/older OS? Running Catalina myself, I cannot reproduce this, haven't updated to Big Sur yet.

**Comment by emctague** [comment] 2021-01-03 19:42
I haven't gotten a chance to test it on Catalina or older, but I have found another oddity - it only does this when listening through AirPods. I'm curious if the same would happen with other bluetooth outputs as well.

**Comment by kondrak** [comment] 2021-01-03 19:46
So it's fine if using standard speakers? Odd indeed  but might be a good starting point for further investigation.

**Comment by kondrak** [comment] 2021-01-03 20:10
Also - does this affect music playback as well?

**Comment by emctague** [comment] 2021-01-04 01:48
I don't think I have a copy of the soundtrack / music files to test with, but since it seems to impact every bit of game audio, incl. background / level ambiance and menu sounds, so I would assume it covers music as well,

**Comment by kondrak** [comment] 2021-01-04 05:38
You can test with any .ogg file, not necessarily original music - it's handled by a different library and I'm trying to see if it's a global playback issue or maybe something specific to the original code only.

**Comment by kondrak** [comment] 2021-01-04 17:20
This should now be fixed on latest master - there was in fact a weird hack for handling different sample rates which manifested only on bluetooth headphones - let me know if it works!

**Closed by kondrak** 2021-01-04 17:20 UTC

**Comment by emctague** [comment] 2021-01-05 03:45
Confirming it works perfectly! Thanks for the quick fix! 👍

**Comment by rullinoiz** [comment] 2022-04-26 06:05
i am also having this issue, monterey with bluetooth headphones and M1. I have tried compiling for both intel and arm and neither have fixed it. sample rates are most likely the issue as i cannot change the rate of mine to 44100khz through audio midi setup to troubleshoot. using 53f17a2 compiled through the terminal

**Comment by kondrak** [comment] 2022-04-26 13:39
@rullinoiz does it happen on headphones only or also if you play via built-in speakers?

**Comment by rullinoiz** [comment] 2022-04-26 14:51
> @rullinoiz does it happen on headphones only or also if you play via built-in speakers?

it's not happening on the built in speakers, only the bluetooth headphones
