### ISSUE TITLE
Fullscreen won't work properly.

### ISSUE THREAD

**Issue by amiga1985** [kondrak/vkQuake2#120] opened 2021-01-16 01:25 UTC
I am using Arch Linux with KDE plasma, and for some reason, whenever I try to go fullscreen on my 1080p monitor, it doesn't seem to work correctly. The game has the right resolution, but isn't fullscreen, so the bottom is slightly cut off. Any reason why this might be? More info: I have two monitors: a 1366*768 screen on the laptop, and an external 1080p monitor. Fullscreen works well on the small laptop screen.

**Comment by kondrak** [comment] 2021-01-16 02:33
Can you post a screenshot?

**Comment by amiga1985** [comment] 2021-01-16 15:18
Here is a video of my issue.

https://user-images.githubusercontent.com/73260114/104815719-33506980-57e4-11eb-8985-de531cec80f4.mp4

**Comment by amiga1985** [comment] 2021-01-16 15:37
Wait... In the config file there is an option called set r_fakeFullscreen. Set this to one, and it works correctly. Maybe this should be on by default?

**Comment by kondrak** [comment] 2021-01-16 18:00
My guess is that at the time iD had some issues with some Linux WMs and they introduced this command to make fullscreen work on some specific setups - I couldn't reproduce this but clearly the issue is there on your system. The Linux code has not aged well, basically it would need a full rewrite to make it work properly and that's a bit out of the scope of this project, so if `r_fakeFullscreen` works for you then I guess we can close this.

**Closed** 2021-01-16 21:21 UTC
