### ISSUE TITLE
ERROR: "Couldn't load maps/bukk1.bsp"  in console

### ISSUE THREAD

**Issue by gamegard68** [kondrak/vkQuake2#140] opened 2021-11-19 08:47 UTC
On manjaro linux I installed and built successfull vkquake2 via AUR. The pak files come from GOG where I bought quake 2.

The Ammo Depot level I can play and save game but not load it because it wants to load an unknown bsp file: "bukk1.bsp" iso "bunk1.bsp".

I looked in your code and the base2 directory for this erroneous "bukk1" string but to no avail.

**Comment by kondrak** [comment] 2021-12-16 11:28
That's odd. Is this 100% reproducible? Can you get that same error on Windows/Mac/other distro?

**Comment by kondrak** [comment] 2021-12-25 22:29
Closing this for now, since there doesn't seem to be any proper way to reproduce this.

**Closed by kondrak** 2021-12-25 22:29 UTC
